# name: Tiniri (Dark)
# author: Vlad Gerasimov
# license: MIT
# upstream: https://tiniri.vlad.studio
# blurb: Optimized for calmness and coziness.

[colors]
ansi = [
  "#1F2122", #Black
  "#c66b67", # Red
  "#68a0a0", # Green
  "#AD8301", # Yellow
  "#F5A571", # Blue
  "#938A80", # Purple
  "#938A80", # Cyan
  "#DBD7D1", # White
]
brights = [
  "#575653", # Black
  "#c66b67", # Red
  "#68a0a0", # Green
  "#D0A215", # Yellow
  "#F5A571", # Blue
  "#938A80", # Purple
  "#938A80", # Cyan
  "#FFFCF0", # White
]
foreground = "#DBD7D1"
background = "#1F2122"

cursor_bg = "#AD514C"
cursor_border = "#AD514C"
cursor_fg = "#DBD7D1"
selection_bg = "#314F52"
selection_fg = "#DBD7D1"

[colors.indexed]

[metadata]
aliases = ["Tiniri Dark"]
name = "Tiniri Dark"
origin_url = "https://tiniri.vlad.studio"
wezterm_version = "Always"
