# name: Tiniri (Light)
# author: Vlad Gerasimov
# license: MIT
# upstream: https://tiniri.vlad.studio
# blurb: Optimized for calmness and coziness.

[colors]
ansi = [
  "#44403C", # Black
  "#AD514C", # Red
  "#538A8A", # Green
  "#AD514C", # Yellow
  "#356B94", # Blue
  "#804C6E", # Magenta
  "#538A8A", # Cyan
  "#DAD8CE", # White
]

brights = [
  "#B7B5AC", # Black
  "#AD514C", # Red
  "#538A8A", # Green
  "#E59793", # Yellow
  "#356B94", # Blue
  "#BD71A4", # Magenta
  "#538A8A", # Cyan
  "#E6E4D9", # White
]

foreground = "#333231"
background = "#FDFCFC"

cursor_bg = "#AD514C"
cursor_border = "#AD514C"
cursor_fg = "#FDFCFC"

selection_fg = "#333231"
selection_bg = "#538A8A44"

[colors.indexed]

[metadata]
aliases = ["Tiniri Light"]
name = "Tiniri Light"
origin_url = "https://tiniri.vlad.studio"
wezterm_version = "Always"
