# name: Tiniri (Dark)
# author: Vlad Gerasimov
# license: MIT
# upstream: https://tiniri.vlad.studio
# blurb: Optimized for calmness and coziness.

[colors]
ansi = [
  "#1F2123", #Black
  "#c66b67", # Red
  "#74A1AA", # Green
  "#CEA182", # Yellow
  "#CEA182", # Blue
  "#938A80", # Purple
  "#74A1AA", # Cyan
  "#E8E5E3", # White
]
brights = [
  "#575653", # Black
  "#D9726C", # Red
  "#9ABAC1", # Green
  "#E5C7B2", # Yellow
  "#E5C7B2", # Blue
  "#ABA49C", # Purple
  "#9ABAC1", # Cyan
  "#FFFCF0", # White
]
foreground = "#E8E5E3"
background = "#1F2123"

cursor_bg = "#AD514C"
cursor_border = "#AD514C"
cursor_fg = "#E8E5E3"
selection_bg = "#314F52"
selection_fg = "#E8E5E3"

split = "#575653"

[colors.indexed]

[metadata]
aliases = ["Tiniri Dark"]
name = "Tiniri Dark"
origin_url = "https://tiniri.vlad.studio"
wezterm_version = "Always"
